version: 2
seeds:
  - name : lkp_divisions
    config:
      schema: "{{env_var('LOOKUPSCHEMA', 'LOOKUP_DEV')}}"
  - name : lkp_categories
    config:
      schema: "{{env_var('LOOKUPSCHEMA', 'LOOKUP_DEV')}}"
  - name : lkp_shippers
    config:
      schema: "{{env_var('LOOKUPSCHEMA', 'LOOKUP_DEV')}}"